### PR TITLE
LaunchScreen modifications.

### PR DESCRIPTION
**Pull request by Shubham0812**
PR for the #33 Issue.

Added a TabBar and a view with the same color as UpcomingView to the storyboard, so that opening the app becomes smoother.

### CODE REVIEW

**Review by pushpinderpalsingh — CHANGES_REQUESTED** [review]
@Shubham0812 do you think we can add a curve to the bottom two parts like in Upcoming View? Can you try that once?

**Comment by Shubham0812** [comment]
@pushpinderpalsingh Yeah, I did think about it and tried out some ways.

Since customization through code is not possible, I created an Image asset with the bottomLeft & bottomRight sides as curved and added it as an ImageView. 

The problem here is that it isn't able to support all kinds of iOS devices, for that we would have to use AspectFill or ScaleToFill using either of them stretches the asset and the rounded corners disappears.

**Comment by pushpinderpalsingh** [comment]
OK, I was searching if we can programmatically make Launch Screen but I don't think we can. I think our present launch screen looks much better. Plus the addition of the tab bar adds a noticeable lag in the launch. I think we should keep our present launch screen. We will need to edit the launch screen once we have implemented a customizable app icon. What do you say? @Shubham0812

**Comment by Shubham0812** [comment]
@pushpinderpalsingh yeah, there was an additional 45-65% increase in the launch time of the app after adding the tabBar. It can be delayed until we find a better approach and modified accordingly.

**Comment by pushpinderpalsingh** [comment]
@Shubham0812 Agreed. I am closing this issue and pr for now.

**Comment by Shubham0812** [comment]
Okay.

**Pull request closed without merging**
