### PR TITLE
Screenshots updated in readme and screenshots folder name changed to Assets

### PR DESCRIPTION
**Pull request by gokulkannan7**
Screenshots updated in readme and screenshots folder name changed to Assets #27

### CODE REVIEW

**Comment by pushpinderpalsingh** [comment]
Remove unwanted assets in the assets folder. And your repo's head is behind my repo. Make sure the heads are even.

**Comment by jamie-brannan** [comment]
Hello @pushpinderpalsingh , just checking that this is the same `Assets` that you intend my issue's `spaceAgencies.md` (#34 ) to be listed under?

I just want to be sure to rebase on these changes if they're going to be merged within this weekend to avoid conflicts. 💪

**Comment by pushpinderpalsingh** [comment]
@jamie-brannan you can just add the spaceAgencies.md under screenshots.

**Comment by pushpinderpalsingh** [comment]
@gokulkannan7 are you working on this?

**Pull request closed without merging**
