### PR TITLE
Add "Watch Now" button for upcoming launches (#46)

### PR DESCRIPTION
**Pull request by jkreller**
iPhone 8 / SE 2:

iPhone 11:

### CODE REVIEW

**Review by pushpinderpalsingh — CHANGES_REQUESTED** [review]
Can you change the location of WatchNowButtonView.swift into a new folder under UIButton and rename it to WatchNowButton.

I think it would look much better if we reduce the size of the WatchNow button and increase the font size kinda like this 

Screenshot 2020-10-23 at 12 26 08 PM

Also, reduce the padding between the buttons and panels for larger screens, only for when watchnow button is visible.

**Comment by jkreller** [comment]
@pushpinderpalsingh Reduce the padding for larger screens? You mean for smaller ones, don't you? 🤔

**Comment by pushpinderpalsingh** [comment]
I think the padding for smaller ones is perfect, we can't reduce them more. On the other hand, the padding between Panels (Launch Date, Launch Site, etc) can be reduced when the watch now button appears. Basically, we will have more padding below the watch now button

**Comment by jkreller** [comment]
@pushpinderpalsingh I just committed the changes, can you review again please? :)

**Comment by pushpinderpalsingh** [comment]
Great job! Thanks for your contribution @all-contributors add @jkreller for code

**Pull request merged**
