### PR TITLE
Space agencies list

### PR DESCRIPTION
**Pull request by jamie-brannan**
Each item contains :
- **API Name**
- **Organisation** behind the API
- **Sector** (Private or public) + country of origin
- **Link** to the API
- **Documentation** of the API
- **Open Source** `bool`

This is a response to issue #34 for 🎃 [Hacktoberfest](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

- [ ] need to add Hacktober label to PR, according to [official update of submission rules](https://hacktoberfest.digitalocean.com/hacktoberfest-update)
- [ ] add self as assignee
- [ ] Link PR #43 to Issue #34

### CODE REVIEW

**Review by pushpinderpalsingh — APPROVED** [review]

**Comment by jamie-brannan** [comment]
Hello again @pushpinderpalsingh , could you help me confirm that this PR contained the `hacktoberfest-accepted` label to ensure it channeled and tallied conform to the revient [submission guideliens](https://hacktoberfest.digitalocean.com/hacktoberfest-update) ?

Thank you again. This has been a great kick off experience for me to contributing. 🚀

**Comment by pushpinderpalsingh** [comment]
I think you don't need that label if your pr is merged, although if required, I will definitely add it.

**Comment by pushpinderpalsingh** [comment]
@all-contributors add @jamie-brannan for code and docs

**Comment by jamie-brannan** [comment]
Thank you @pushpinderpalsingh 😊

I think you're right, it's not required if the repo is labeled as a part of Hacktoberfest. However given how much they're struggling with spam this year I think it's safer just to add `hacktoberfest-accepted` for clarity and their convenience. 🙏

**Comment by pushpinderpalsingh** [comment]
Ok I will add hacktoberfest-accepted

**Pull request merged**
