### PR TITLE
Added customising app icon feature

### PR DESCRIPTION
**Pull request by rajhraval1**
Based on #47 I have added the stated feature in this PR.

Reverted back to original design.
Added a button to open a page sheet which provides a segmented control to change the app icon.
State is saved by UserDefaults.

Screenshots for the stated featured:

|Click on Change App Icon|Select an App Icon|Icon is Changed|
|--|--|--|
|Simulator Screen Shot - iPhone 12 Pro - 2020-10-26 at 16 47 44| Simulator Screen Shot - iPhone 12 Pro - 2020-10-26 at 16 47 48| Simulator Screen Shot - iPhone 12 Pro - 2020-10-26 at 16 47 50|

Waiting for feedback and review!

### CODE REVIEW

**Review by pushpinderpalsingh — CHANGES_REQUESTED** [review]
Can you make something like below? I think that would look much better.
Screenshot 2020-10-26 at 11 10 45 PM
You might need to change the font size of the button. Also, don't change the constraints for the "About SpaceDash" view.

For the screen in which we choose the app icon, can you implement TableView like earlier? I think that looked much better. Just don't add a name for each version of the app icon. Can you use app custom colours ie DashBlack and DashCream for background and tableview cells respectively?

**Comment by rajhraval1** [comment]
That actually doesn't look ideal in my opinion.
I think entire table view controller (like Settings App) is better or the Page Sheet for Icon Picker is better.

Because, mostly they (Icon Picker) are either collection view based or table view based in form of sheet/full page.

For a new redesign, I have much better plans for the About Module.

**Comment by pushpinderpalsingh** [comment]
Ok, since you are saying you plan to redesign About Screen, I will accept this design but with some minor adjustments. Remove the license button with all its supporting code and resize the font of Change App Icon to match that of the privacy policy button.

**Comment by rajhraval1** [comment]
Done with the changes.

**Review by pushpinderpalsingh — CHANGES_REQUESTED** [review]
I think after some minor changes, your pr will be ready to be merged.

**Comment by pushpinderpalsingh** [comment]
Thanks for your contribution! @all-contributors add @rajhraval1 for code

**Pull request merged**
